version: "3.8"

networks:
  task-tracker:
    driver: bridge

services:
  db:
    image: mysql:latest
    container_name: task-tracker_db
    cap_add:
      - SYS_NICE
    command: --mysql-native-password=ON
    restart: always
    environment:
      MYSQL_DATABASE: task-tracker
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./server/db-data:/var/lib/mysql
    ports:
      - 4306:3306
    networks:
      - task-tracker
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend_image
    container_name: task-tracker_api
    depends_on:
      - db
    user: 1000:1000
    working_dir: /home/task-tracker
    ports:
      - 8848:8848
    volumes:
      - ./server:/home/task-tracker
    networks:
      - task-tracker
